- name: ausopen_2023_wta
  tour: WTA
  tournament: australian open
  year: 2023
  sackmann_csv: data/tennis_wta/wta_matches_2023.csv
  snapshots_csv: parsed/betfair_tennis_snapshots.csv
  output_csv: data/processed/ausopen_2023_wta_clean_snapshot_matches.csv

- name: frenchopen_2023_wta
  tour: WTA
  tournament: roland garros
  year: 2023
  sackmann_csv: data/tennis_wta/wta_matches_2023.csv
  snapshots_csv: parsed/betfair_tennis_snapshots.csv
  output_csv: data/processed/frenchopen_2023_wta_clean_snapshot_matches.csv

- name: usopen_2023_wta
  tour: WTA
  tournament: us open
  year: 2023
  sackmann_csv: data/tennis_wta/wta_matches_2023.csv
  snapshots_csv: parsed/betfair_tennis_snapshots.csv
  output_csv: data/processed/usopen_2023_wta_clean_snapshot_matches.csv
